version: "3"

services:
  phoenix:
    build:
      context: ./
    environment:
      PGUSER: postgres
      PGPASSWORD: postgres
      PGDATABASE: backend_app_feirinha
      PGHOST: db
      # porta na qual eu vou criar o banco
      PGPORT: 5432
    ports:
      - 4000:4000
    depends_on:
      - db

  db:
    image: postgres:12-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
    restart: always
    volumes: 
      - pgdata:/var/lib/postgresql/data
    ports:
    # minha_porta:porta_do_container
      - 5433:5432

volumes:
  pgdata:    